added unit-tests
lilymammadova/HotelApplication pull request #2
Opened 2024-11-08 15:35 UTC by lilymammadova

2024-11-08 15:43 UTC, Alexmansar requested changes
@lilymammadova Hi) in general good job) 
Have general comments regarding comments
and what about CI?

2024-11-08 15:43 UTC, Alexmansar commented on src/test/java/org/liliya/hotelapp/service/ApartmentServiceImplTest.java
> +    //Test for  method register
no comments needed

2024-11-08 15:43 UTC, Alexmansar commented on src/test/java/org/liliya/hotelapp/service/ApartmentServiceImplTest.java
> +    //Test for method reserve
same in general

2024-11-08 15:43 UTC, Alexmansar commented on src/test/java/org/liliya/hotelapp/ui/ConsoleTest.java
> +    }
try to remove it

2024-11-08 15:45 UTC, Alexmansar commented
@lilymammadova 
Fix your pom xml
![image](https://github.com/user-attachments/assets/d8020fce-31fe-4679-a5a0-c707be74f266)

2024-11-10 06:20 UTC, lilymammadova commented on src/test/java/org/liliya/hotelapp/service/ApartmentServiceImplTest.java
> +    //Test for  method register
fixed

2024-11-10 06:21 UTC, lilymammadova commented on src/test/java/org/liliya/hotelapp/service/ApartmentServiceImplTest.java
> +    //Test for method reserve
fixed

2024-11-10 06:21 UTC, lilymammadova commented on src/test/java/org/liliya/hotelapp/ui/ConsoleTest.java
> +    }
removed

2024-11-10 06:23 UTC, lilymammadova commented
@Alexmansar fixed all comments and about CI, the workflow already here : [https://github.com/lilymammadova/HotelApplication/blob/master/.github/workflows/main.yml](url) , I just already pushed it to master branch I thought that we need only checks in pull requests

2024-11-10 15:13 UTC, Alexmansar approved these changes
@lilymammadova Hi)) please, merge it) good job

2024-11-11 09:02 UTC, merged